// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirInExplorer(arg1) {
  return window['go']['main']['App']['OpenDirInExplorer'](arg1);
}

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}

export function RestartServer() {
  return window['go']['main']['App']['RestartServer']();
}

export function UpdateDefaultDir(arg1) {
  return window['go']['main']['App']['UpdateDefaultDir'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function WindowHide() {
  return window['go']['main']['App']['WindowHide']();
}

export function WindowShow() {
  return window['go']['main']['App']['WindowShow']();
}
