// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDirInExplorer(arg1) {
  return window['go']['main']['App']['OpenDirInExplorer'](arg1);
}

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}
