// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {server} from '../models';

export function ExitApp():Promise<void>;

export function GetAppConfig():Promise<server.Config>;

export function OpenDirInExplorer(arg1:string):Promise<void>;

export function OpenDirectory():Promise<Record<string, any>>;

export function RestartServer():Promise<void>;

export function ToolsParseToken(arg1:string):Promise<server.UserToken>;

export function ToolsPingHost(arg1:any,arg2:string):Promise<Record<string, any>>;

export function UpdateConfigData(arg1:Record<string, any>):Promise<Record<string, any>>;

export function Version():Promise<string>;

export function WindowHide():Promise<void>;

export function WindowShow():Promise<void>;
