// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExitApp() {
  return window['go']['main']['App']['ExitApp']();
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function OpenDirInExplorer(arg1) {
  return window['go']['main']['App']['OpenDirInExplorer'](arg1);
}

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}

export function RestartServer() {
  return window['go']['main']['App']['RestartServer']();
}

export function ToolsPingHost(arg1, arg2) {
  return window['go']['main']['App']['ToolsPingHost'](arg1, arg2);
}

export function UpdateConfigData(arg1) {
  return window['go']['main']['App']['UpdateConfigData'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function WindowHide() {
  return window['go']['main']['App']['WindowHide']();
}

export function WindowShow() {
  return window['go']['main']['App']['WindowShow']();
}
